eventsdjango/TestBackend/urls.py
from django.urls import path, include, re_path
from django.views.static import serve
from django.contrib import admin
from django.conf import settings

from events.views import index

from users.views import login, details

urlpatterns = [
	path("admin/", admin.site.urls),
	path("api/v0/events/", include(("events.urls", "events"), namespace="events")),
	path("api/v0/users/", include(("users.urls", "users"), namespace="users")),
	path("", index, name="index"),
	path("signup", index, name="signup"),
	path("login", login, name="login"),
	path("detailsweb/<int:id>/", details, name="detailsweb"),
	re_path(r"^static/(?P<path>.*)$", serve,{"document_root": settings.STATIC_ROOT}),
]

eventsdjango/events/urls.py
from django.urls import path
from .views import EventsAPIView, EventsMembersAPIView


urlpatterns = [
	path("", EventsAPIView.as_view(), name = "list"),
	path("members/", EventsMembersAPIView.as_view(), name = "members"),
]

eventsdjango/users/urls.py
from django.urls import path
from .views import UserAuthAPI, UserAPI, UserDetailAPI

urlpatterns = [
	path("auth/", UserAuthAPI.as_view(), name="auth"),
	path("", UserAPI.as_view(), name="action"),
	path("details/", UserDetailAPI.as_view(), name="details"),
]

eventsdjango/events/models.py
from django.db import models
from django.contrib.auth import get_user_model

class Event(models.Model):
	id = models.BigAutoField(primary_key = True, null = False, editable = False, name = "id")
	title = models.CharField(max_length=128, null=False, name="title")
	text = models.CharField(max_length=512, null=False, name="text")
	owner = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name="owner")
	members = models.ManyToManyField(get_user_model(), related_name="members")
	add_date = models.DateTimeField(auto_now_add=True, null=False, name="add_date")

eventsdjango/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from .managers import CustomUserManager

class User(AbstractUser):
	id = models.BigAutoField(primary_key = True, null = False, editable = False, name = "id")
	login = models.CharField(max_length = 128, null = False, name = "login", unique=True)
	password = models.CharField(max_length = 256, null = False, name = "password")
	name = models.CharField(max_length = 64, null = False, name = "name")
	lastname = models.CharField(max_length = 64, null = False, name = "lastname")
	birth_date = models.DateField(null = True, name = "birth_date")
	
	email = None
	username = None
	last_login = None

	USERNAME_FIELD = "login"
	REQUIRED_FIELDS = ["name", "lastname"]

	objects = CustomUserManager()

	def __str__(self):
		return self.login

eventsdjango/events/views.py
from django.http import HttpResponse
from django.template import loader

from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.permissions import IsAuthenticated
from rest_framework.authentication import TokenAuthentication

from .models import Event
from .serializers import EventSerializer

class EventsAPIView(APIView):
	permission_classes = [IsAuthenticated]
	authentication_classes = (TokenAuthentication,)

	def get(self, request):
		data = Event.objects.all()
		return Response({"error": None , "result": EventSerializer(data, many=True).data})

	def post(self, request):
		output = {"error": None, "result": None}
		serializer = EventSerializer(data = request.data)
		if(not serializer.is_valid(raise_exception=False)):
			output["error"] = serializer.errors
			return Response(output)
		serializer.save(owner = request.user)
		output["result"] = serializer.data
		return Response(output)

	def delete(self, request):
		output = {"error": None, "result": None}
		id = request.data.get("id")
		if(id):
			try:
				event = Event.objects.filter(id=id)
				if(event):
					event = event.first()
					if(event.owner == request.user):
						event.delete()
						output["result"] = "Success"
					else:
						output["error"] = "You are not owner of this event"
				else:
					output["error"] = "Event with this id not found"
			except Exception as e:
				output["error"] = str(e)
		else:
			output["error"] = "'id' not found"
		return Response(output)

class EventsMembersAPIView(APIView):
	permission_classes = [IsAuthenticated]
	authentication_classes = (TokenAuthentication,)

	def post(self, request):
		output = {"error": None, "result": None}
		id = request.data.get("id")
		if(id):
			event = Event.objects.filter(id=id)
			if(event):
				event = event.first()
				if(not event.members.filter(id=request.user.id).exists()):
					event.members.add(request.user)
					output["result"] = "Success"
				else:
					output["error"] = "You already member of this event"
			else:
				output["error"] = "Event with this id not found"
		else:
			output["error"] = "'id' not found"
		return Response(output)

	def delete(self, request):
		output = {"error": None, "result": None}
		id = request.data.get("id")
		if(id):
			event = Event.objects.filter(id=id)
			if(event):
				event = event.first()
				if(event.members.filter(id=request.user.id).exists()):
					event.members.remove(request.user)
					output["result"] = "Success"
				else:
					output["error"] = "You are not member of this event"
			else:
				output["error"] = "Event with this id not found"
		else:
			output["error"] = "'id' not found"
		return Response(output)


def index(request):
	template = loader.get_template("events.html")
	return HttpResponse(template.render({},request))

eventsdjango/users/views.py
import json
from rest_framework.permissions import AllowAny, IsAuthenticated
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.authentication import TokenAuthentication
from rest_framework.authtoken.models import Token
from rest_framework import status

from .serializers import UserSerializer
from django.contrib.auth import get_user_model

from django.http import HttpResponse
from django.template import loader


# Class based view to Get user Details using Token Authentication
class UserDetailAPI(APIView):
	permission_classes = [IsAuthenticated]
	authentication_classes = (TokenAuthentication,)
	def post(self, request, *args, **kwargs):
		output = {"error": None, "result": None}
		id = request.data.get("id")
		if(id):
			user = get_user_model().objects.filter(id=id)
			if(user):
				serializer = UserSerializer(user.first())
				output["result"] = serializer.data
			else:
				output["error"] = "User with this id not found"
		else:
			user = get_user_model().objects.all()
			serializer = UserSerializer(user, many=True)
			output["result"] = serializer.data
		return Response(output)
		

class UserAPI(APIView):
	#permission_classes = [IsAuthenticated]
	permission_classes = [AllowAny]
	#authentication_classes = (TokenAuthentication,)
	
	def post(self, request, *args, **kwargs):
		serializer = UserSerializer(data = request.data)
		if serializer.is_valid():
			serializer.save()
			return Response({"error": None, "result": serializer.data}, status=status.HTTP_201_CREATED)
		return Response({"error": serializer.errors, "result": None}, status=status.HTTP_400_BAD_REQUEST)
	
	def delete(self, request, *args, **kwargs):
		if(not request.user.is_authenticated):
			return Response({"error": "User not authorized", "result": None}, status=status.HTTP_401_UNAUTHORIZED)
		try:
			request.user.delete()
			return Response({"error": None, "result": "Successfully deleted."}, status=status.HTTP_200_OK)
		except Exception as e:
			return Response({"error": str(e), "result": None}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)
	
class UserAuthAPI(APIView):
	permission_classes = []
	
	def post(self, request, *args, **kwargs):
		if(not request.user.is_authenticated):
			login = request.data.get('login')
			password = request.data.get('password')
			users = get_user_model().objects.filter(login=login)
			if(users):
				user = users.first()
				if(user.check_password(password)):
					token, _ = Token.objects.get_or_create(user=user)
					request.user = user
					serializer = UserSerializer(user)
					return Response({"error": None, "result": {"token": token.key, "user": serializer.data}}, status=status.HTTP_200_OK)
			return Response({"error": "Invalid credentials", "result": None}, status=status.HTTP_401_UNAUTHORIZED)
		else:
			return Response({"error": None, "result": {"token": Token.objects.get(user=request.user).key, "user": UserSerializer(request.user).data}}, status=status.HTTP_200_OK)

	def delete(self, request, *args, **kwargs):
		if(not request.user.is_authenticated):
			return Response({"error": "user not authorized", "result": None}, status=status.HTTP_401_UNAUTHORIZED)
		try:
			request.user.auth_token.delete()
			return Response({"error": None, "result": "Successfully logged out."}, status=status.HTTP_200_OK)
		except Exception as e:
			return Response({"error": str(e), "result": None}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)

def login(request):
	template = loader.get_template("user_action.html")
	return HttpResponse(template.render({}, request))

def details(request, id):
	template = loader.get_template("user_details.html")
	UserSerializer()
	user = get_user_model().objects.filter(id=id)
	if(user):
		serializer = UserSerializer(user.first())
		return HttpResponse(template.render(serializer.data, request), status=200)
	else:
		return HttpResponse(template.render({}, request), status=404)

eventsdjango/templates/base.html
{% include "upper.html" %}

{{content}}

{% include "lower.html" %}

eventsdjango/templates/events.html
{% load static %}
{% include "upper.html" %}
<link rel="stylesheet" href="{% static 'css/events.css' %}">

<div class="events_scroll Flipped">
	<div class="group_title" id="title_all">Все события</div>
	<div class="group" id="group_all">
	</div>
	<div class="group_title" id="title_my">Мои события</div>
	<div class="group" id="group_my">
	</div>
	<div class="group" style="border: none">
		<div class="event" id="add_event_btn" onclick="ADD_EVENT()">Добавить</div>
	</div>
</div>
<div id="event_window">
	<input type="text" class="title" id="title" maxlength="128" value="Название" required>
	<textarea type="text" id="content" placeholder="Контент" maxlength="512" required>Контент</textarea>
	<div id="date">дата</div>
	<br>
	<div class="title" id="title_members">Участники</div>
	<div id="members">
	</div>
	<br>
	<div class="ActionButtons">
		<div class="ActionButton" id="add_event">Добавить событие</div>
		<div class="ActionButton" id="del_event">Удалить событие</div>
		<!--div class="ActionButton" id="edit_event">Изменить событие</div-->
		<div class="ActionButton" id="add_member">Принять участие</div>
		<div class="ActionButton" id="del_member">Отклонить участие</div>
	</div>
</div>
<script src="{% static 'scripts/events.js' %}"></script>

{% include "lower.html" %}

eventsdjango/templates/lower.html
		</div>
		<div id="footer" class="footer">
			&copy; TitanX(Гусев Сергей, email: sergey_gusev_007@mail.ru)
			<br>
			<!--a href="TERMS">Пользовательское соглашение</a>
			|
			<a href="PRIVACY">Политика конфиденциальности</a-->
		</div>
	</body>
</html>

eventsdjango/templates/upper.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
	<head>
		<meta name="Description" content="Events">
		<meta charset="utf-8" name="viewport" content="width=device-width, initial-scale=1">
		<title>Events</title>
		<link rel="icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
		<link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
		<script src="{% static 'scripts/jquery.min.js' %}" type="text/javascript"></script>
		<script>
			var LOGIN_URL = "{% url 'users:auth' %}";
			var REG_URL = "{% url 'users:action' %}";
			var DETAILS_URL = "{% url 'users:details' %}";
			var EVENTS_LIST_URL = "{% url 'events:list' %}";
			var EVENTS_MEMBERS_URL = "{% url 'events:members' %}";
			var MAIN_WEB_URL = "{% url 'index' %}";
			var LOGIN_WEB_URL = "{% url 'login' %}";
			var DETAILS_WEB_URL = "{% url 'detailsweb' 1 %}";
		</script>
		<script src="{% static 'scripts/Base.js' %}"></script>
		<link rel="stylesheet" href="{% static 'css/main.css' %}">
	</head>
	<body>
		<div class="topnav">
			<a onclick="window.location.href = MAIN_WEB_URL">Events</a>
			<a id="username"></a>
			<a id="login" onclick="window.location.href = LOGIN_WEB_URL">Войти</a>
			<a id="logout" onclick="LOGOUT()">Выйти</a>
		</div>
		{% csrf_token %}
		<div id="SiteMessages"></div>
		<script type="text/javascript">
			const SiteMessages = document.getElementById("SiteMessages");
			const login_el = document.getElementById("login");
			const logout_el = document.getElementById("logout");
			const username_el = document.getElementById("username");
			login_el.style.display = "none";
			logout_el.style.display = "none";
			username_el.style.display = "none";
			LOGIN();
		</script>
		<div class="display">

eventsdjango/templates/user_action.html
{% load static %}
{% include "upper.html" %}
<script type="text/javascript">
	function ACTION() {
		var data = {};
		if (login.value && password.value) {
			data["login"] = login.value;
			data["password"] = password.value;
			if(name.value && lastname.value) {
				data["name"] = name.value;
				data["lastname"] = lastname.value;
				fetch(REG_URL, {
					method: "POST",
					body: JSON.stringify({}),
					headers: {
						"Content-type": "application/json; charset=UTF-8",
						"X-CSRFToken": getCookie("csrftoken"),
						"Authorization": getCookie("Token"),
					},
				})
				.then((response) => response.json())
				.then((response) => {
					if(response.error !== null) throw Error(response.error);
					create_message(1, "Успешная авторизация");
					window.location.href = MAIN_WEB_URL;
				})
				.catch((err) => {
					create_message(-1, "Ошибка при регистрации:", err.message);
				})
			} else {
				LOGIN(data);
			}
		} else {
			create_message(-1, "Поля логина и пароля должны быть заполнены");
		}
	}
	function ISLOGIN(){
		if (login.value && password.value) {
			regform.style.display="block";
			if(name.value && lastname.value) {
				actionbutton.value = "Регистрация";
				actionbutton.style.display="block";
			} else {
				actionbutton.value = "Войти";
				actionbutton.style.display="block";
			}
		} else {
			regform.style.display="none";
			actionbutton.value = "Войти";
			actionbutton.style.display="none";
		}
	}
</script>

<link rel="stylesheet" href="{% static 'css/action.css' %}">

<form class="action_form" action="javascript:ACTION()" accept-charset="UTF-8">
	<label for="reg_login">Логин</label>
	<input type="text" class="input-box" id="reg_login" minlength="2" autocomplete="username" maxlength="64" value="" required>
	
	<label for="reg_password">Пароль</label>
	<input type="password" class="input-box" id="reg_password" autocomplete="new-password" minlength="2" maxlength="255" value="" required>

	<div id="reg_form">
		<label for="reg_name">Имя</label>
		<input type="text" class="input-box" id="reg_name" autocomplete="name" minlength="1" maxlength="64" value="">
		
		<label for="reg_lastname">Фамилия</label>
		<input type="text" class="input-box" id="reg_lastname" autocomplete="family-name" minlength="1" maxlength="64" value="">
	</div>
	<input type="submit" value="Войти" id="ActionButton" class="action-btn">
</form>
<script type="text/javascript">
	const login = document.getElementById("reg_login");
	const password = document.getElementById("reg_password");

	const name = document.getElementById("reg_name");
	const lastname = document.getElementById("reg_lastname");
	
	
	const actionbutton = document.getElementById("ActionButton");

	const regform = document.getElementById("reg_form");
	regform.style.display="none";
	actionbutton.style.display="none";
	const inputHandler = function(e) {
		ISLOGIN()
	}
	const fields = [login, password, name, lastname];
	for (var i = 0; i < 4; i++) {
		fields[i].addEventListener("input", inputHandler);
		fields[i].addEventListener("propertychange", inputHandler);
	}
</script>
{% include "lower.html" %}

eventsdjango/templates/user_details.html
{% load static %}
{% include "upper.html" %}
<link rel="stylesheet" href="{% static 'css/action.css' %}">

<div class="action_form">
	<label>ID</label>
	<input type="text" class="input-box" value="{{id}}" readonly="readonly">
	<label>Логин</label>
	<input type="text" class="input-box" value="{{login}}" readonly="readonly">
	<label>Имя</label>
	<input type="text" class="input-box" value="{{name}}" readonly="readonly">
	<label>Фамилия</label>
	<input type="text" class="input-box" value="{{lastname}}" readonly="readonly">
</div>

{% include "lower.html" %}